### 🧍 Registro de usuario
POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
  "username": "viajero1",
  "email": "viajero1@example.com",
  "password": "password123"
}


### 🔑 Login de usuario
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "username": "viajero1",
  "password": "password123"
}

### Crear viaje (requiere token)
POST http://localhost:8000/api/trips/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU5NDA1LCJpYXQiOjE3NjE2NTkxMDUsImp0aSI6IjljNmM3Y2RiMDc1MDQ2MmU5YjRmZGNlNjRjN2JmZmUwIiwidXNlcl9pZCI6IjEifQ.8GyPyfrpKOTALBiEm01PtOs8puQqTvhvpD35EaPto4k

{
  "title": "Aventura en Islandia",
  "description": "Explorando los fiordos y cascadas.",
  "location": "Reikiavik, Islandia",
  "start_date": "2025-08-01",
  "end_date": "2025-08-15",
  "is_public": true
}

### Listar viajes públicos
GET http://localhost:8000/api/trips/

### Detalle de viaje
GET http://localhost:8000/api/trips/2/

### Eliminar viaje
DELETE http://localhost:8000/api/trips/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU5NDA1LCJpYXQiOjE3NjE2NTkxMDUsImp0aSI6IjljNmM3Y2RiMDc1MDQ2MmU5YjRmZGNlNjRjN2JmZmUwIiwidXNlcl9pZCI6IjEifQ.8GyPyfrpKOTALBiEm01PtOs8puQqTvhvpD35EaPto4k

### Crear entrada (requiere token)
POST http://localhost:8000/api/trips/2/entries/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU5NDA1LCJpYXQiOjE3NjE2NTkxMDUsImp0aSI6IjljNmM3Y2RiMDc1MDQ2MmU5YjRmZGNlNjRjN2JmZmUwIiwidXNlcl9pZCI6IjEifQ.8GyPyfrpKOTALBiEm01PtOs8puQqTvhvpD35EaPto4k
Content-Type: application/json

{
  "title": "Día 1 - Llegada a Reikiavik",
  "content": "Llegué al aeropuerto y vi la aurora boreal por primera vez.",
  "latitude": 64.1265,
  "longitude": -21.8174
}

### Ver entradas del viaje
GET http://localhost:8000/api/trips/2/entries/

### Ver detalle de una entrada
GET http://localhost:8000/api/entries/1/

### Eliminar entrada
DELETE http://localhost:8000/api/entries/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU5NDA1LCJpYXQiOjE3NjE2NTkxMDUsImp0aSI6IjljNmM3Y2RiMDc1MDQ2MmU5YjRmZGNlNjRjN2JmZmUwIiwidXNlcl9pZCI6IjEifQ.8GyPyfrpKOTALBiEm01PtOs8puQqTvhvpD35EaPto4k

### Ver comentarios de una entrada
GET http://localhost:8000/api/entries/1/comments/

### Crear comentario (requiere token)
POST http://localhost:8000/api/entries/1/comments/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "text": "¡Qué experiencia tan increíble! 😍"
}